### PR TITLE
Add links to control panel navbar

### LINKED ISSUE #1479: [ENH] - Add endpoints to JHub control panel
### Feature description

When on the jupyterhub control panel, it would be great to link to all of the endpoints (`argo`, `conda-store`, `monitoring`, `auth`). 

### Value and/or benefit

This would make those endpoint discoverable. At the present, it requires remembering what those endpoints are in order to navigate there. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aktech**
Fixes https://github.com/Quansight/qhub/issues/1479

Demo:
Screenshot 2022-10-12 at 10 42 21 am

### CODE REVIEW

**Comment by dharhas** [comment]
@aktech 

instead of Argo maybe Argo Workflows 
instead of Conda-Store maybe Environment Management
instead of Auth maybe User Management

What do you think?

**Review by viniciusdc — APPROVED** [review]
LGTM, thanks @aktech

**Comment by aktech** [comment]
@dharhas yep, that makes sense. Updated now.

**Review by iameskild — APPROVED** [review]
🎉

**Pull request merged**
